"""
Master Cotton Ginners List data source.

Cotton gins and cooperatives - the closest public data to cotton growers.
Gins process cotton from growers; cooperatives are grower-owned.
Contact these to reach cotton growers in each region.

Sources:
- FSA Master Cotton Ginners List
- cottongins.org state lists
- PCCA/Farmers Cooperative Compress
"""

import os
from pathlib import Path
from typing import Iterator

import requests

from ..config import DATA_DIR

MASTER_GINNERS_URL = "https://www.fsa.usda.gov/media/11107"

# Cotton gins/cooperatives from cottongins.org (full state lists)
# Format: (name, city, state)
COTTON_GINS_AND_COOPS = [
    # Alabama - 22 gins (cottongins.org)
    ("5 Lock Gin and Warehouse", "Dothan", "AL"),
    ("Associated Growers Co-op", "Athens", "AL"),
    ("Black Belt Gin", "Selma", "AL"),
    ("Carrville Gin Co", "Tallassee", "AL"),
    ("Cherokee Gin & Cotton Co", "Centre", "AL"),
    ("Coffee Gin Company", "Enterprise", "AL"),
    ("Cotton Producers Co-op", "New Market", "AL"),
    ("Cotton Producers Co-op", "Tuscumbia", "AL"),
    ("Covington Gin Co", "Andalusia", "AL"),
    ("Frank Currie Gin Company", "Atmore", "AL"),
    ("Henry County Gin", "Headland", "AL"),
    ("Hillsboro Gin", "Hillsboro", "AL"),
    ("Holtville Gin Co-op", "Deatsville", "AL"),
    ("Milstead Farm Group", "Shorter", "AL"),
    ("Oakland Gin Co", "Florence", "AL"),
    ("Rainbow Gin Company", "Blountsville", "AL"),
    ("Scruggs & Vaden Gin Co", "Florence", "AL"),
    ("Segrest Brothers Gin", "Shorter", "AL"),
    ("Servico Gin", "Courtland", "AL"),
    ("Sowega Cotton Gin", "Hartford", "AL"),
    ("Sweet Water Gin", "Sweet Water", "AL"),
    ("Yeager Gin Company", "Moulton", "AL"),
    # Arizona - 7 gins
    ("Chandler Ginning Co", "Casa Grande", "AZ"),
    ("Farmers Gin", "Buckeye", "AZ"),
    ("Glenbar Gin", "Pima", "AZ"),
    ("Pinal Gin", "Stanfield", "AZ"),
    ("River Co-op Gin", "Coolidge", "AZ"),
    ("Safford Valley Cotton Growers", "Safford", "AZ"),
    ("Yuco Gin", "Yuma", "AZ"),
    # Arkansas - 24 gins
    ("Adams Land Co. Gin", "Leachville", "AR"),
    ("Black Oak Gin Co", "Black Oak", "AR"),
    ("Childress Gin & Elevator", "Monette", "AR"),
    ("Crittenden Gin Company", "Crawfordsville", "AR"),
    ("Cotton Growers, Inc", "Dell", "AR"),
    ("Deyampert Gin", "Wilmot", "AR"),
    ("Epstein Gin Co", "Lake Village", "AR"),
    ("Farmers First Gin", "Blytheville", "AR"),
    ("GPS Gin Co", "Portland", "AR"),
    ("Graves Gin Co", "Rector", "AR"),
    ("Kiech-Shauver Miller Gin Co", "Monette", "AR"),
    ("Langston Enterprises", "Blytheville", "AR"),
    ("Lee Wilson & Co", "Wilson", "AR"),
    ("McClendon, Mann & Felton Gin", "Marianna", "AR"),
    ("McGehee Producers Gin", "McGehee", "AR"),
    ("Monette Co-op", "Monette", "AR"),
    ("Portland Gin & Warehouse", "Portland", "AR"),
    ("Rabbit Ridge Cotton Warehouse", "Lepanto", "AR"),
    ("Senter & Sons Gin, Inc.", "Osceola", "AR"),
    ("Service Co-op Gin", "Marvell", "AR"),
    ("Southland Gin", "Lake City", "AR"),
    ("Taylor Gin", "Gould", "AR"),
    ("Tripp Gin Company", "Griffithville", "AR"),
    ("WinCott Gin Co", "Winchester", "AR"),
    # California - 7 gins
    ("County Line Gin", "Hanford", "CA"),
    ("Dos Palos Co-op Gin", "Dos Palos", "CA"),
    ("Farmer's Co-op Gin", "Buttonwillow", "CA"),
    ("Mid-Valley Cotton Growers", "Tulare", "CA"),
    ("Modern Ginning Co", "Blythe", "CA"),
    ("Westhaven Cotton Co", "Lemoore", "CA"),
    ("West Island Co-op Gin", "Lemoore", "CA"),
    # Florida - 4 gins
    ("Burkhead Gin Co", "Jay", "FL"),
    ("Clover Leaf Gin", "Marianna", "FL"),
    ("Golden Gin Warehouse", "Jay", "FL"),
    ("West Florida Gin Co", "Walnut Hill", "FL"),
    # Georgia - 41 gins
    ("Arabi Gin", "Arabi", "GA"),
    ("Boston Gin Co", "Boston", "GA"),
    ("BTC Gin Co", "Quitman", "GA"),
    ("Bulloch Gin Co", "Brooklet", "GA"),
    ("Candler Gin & Warehouse Co", "Metter", "GA"),
    ("Clover Leaf Gin", "Donalsonville", "GA"),
    ("Coffee County Gin Co", "Douglas", "GA"),
    ("Coley Gin & Fertilizer", "Vienna", "GA"),
    ("Collins Gin", "Waynesboro", "GA"),
    ("Cotton Fortunes", "Leesburg", "GA"),
    ("Decatur Gin Company", "Bainbridge", "GA"),
    ("Dixon Cotton Gin", "Enigma", "GA"),
    ("Doerun Gin Co", "Doerun", "GA"),
    ("Dooly County Gin", "Vienna", "GA"),
    ("Early County Gin", "Blakely", "GA"),
    ("Edison Gin Co-op", "Edison", "GA"),
    ("Farmer's Gin & Peanut Co", "Moultrie", "GA"),
    ("Farmer's Gin & Storage Co", "Wadley", "GA"),
    ("Findlay Gin", "Vienna", "GA"),
    ("Four Corners Gin Co", "Meigs", "GA"),
    ("Funston Gin Co", "Funston", "GA"),
    ("Griggs Gin", "Pinehurst", "GA"),
    ("Heart Of Georgia Peanut & Gin", "Hawkinsville", "GA"),
    ("McCleskey Cotton Co", "Dawson", "GA"),
    ("Miller County Cotton Co", "Colquitt", "GA"),
    ("Mobley Gin Co", "Doerun", "GA"),
    ("Norman Park Gin & Warehouse", "Norman Park", "GA"),
    ("Omega Gin Co", "Tifton", "GA"),
    ("Osceola Cotton Co", "Ocilla", "GA"),
    ("Pinecliff Planters Cotton Gin", "Camilla", "GA"),
    ("Quality Gin Inc.", "Shellman", "GA"),
    ("Riverside Gin & Storage", "Midville", "GA"),
    ("Screven Gin Co", "Sylvania", "GA"),
    ("Sconyer's Gin & Warehouse", "Sycamore", "GA"),
    ("South Central Georgia Gin", "Enigma", "GA"),
    ("Southeastern Gin & Peanut", "Surrency", "GA"),
    ("Southern Gin", "Pelham", "GA"),
    ("South Georgia Gin", "Hazlehurst", "GA"),
    ("Sowega Cotton Gin", "Climax", "GA"),
    ("Sumter County Producers Gin", "Americus", "GA"),
    ("The Cotton Gin", "Lenox", "GA"),
    ("Tri County Gin", "Taylorsville", "GA"),
    ("Tri-County Gin", "Douglas", "GA"),
    ("Trico Gin & Peanut", "Unadilla", "GA"),
    ("Worth Gin & Warehouse", "Sylvester", "GA"),
    # Louisiana - 13 gins
    ("Armistead Gin Co", "Coushatta", "LA"),
    ("Associated Producers Co-op", "Winnsboro", "LA"),
    ("Browning Gin Co", "Crowville", "LA"),
    ("Caddo Farmers Gin Inc", "Belcher", "LA"),
    ("C-C Planters Gin", "Jonesville", "LA"),
    ("Gilliam Gin Co", "Gilliam", "LA"),
    ("Hollybrook Gin", "Lake Providence", "LA"),
    ("Joe's Bayou Gin", "Lake Providence", "LA"),
    ("McNutt Gin Co", "Boyce", "LA"),
    ("Planters Gin", "St. Joseph", "LA"),
    ("Rayville Producers Gin", "Rayville", "LA"),
    ("Tanner Gin", "Ferriday", "LA"),
    ("Tensas Co-op Gin", "Newellton", "LA"),
    # Mississippi - 27 gins
    ("Big Creek Gin", "Lyon", "MS"),
    ("Bobo-Moseley Gin Co", "Lyon", "MS"),
    ("Bogue Chitto Gin", "Macon", "MS"),
    ("Como Consolidated Gin Co", "Como", "MS"),
    ("Crossroads Gin", "Schlater", "MS"),
    ("Double B Gin", "Randolph", "MS"),
    ("Due West Gin", "Cary", "MS"),
    ("Farmers Gin", "Hamilton", "MS"),
    ("Farrell Gin Co", "Clarksdale", "MS"),
    ("Four County Gin", "Calhoun", "MS"),
    ("Greenwood Gin", "Greenwood", "MS"),
    ("Grundfest & Klaus Gin", "Cary", "MS"),
    ("Hi Grade Farm Supply & Gin", "Winona", "MS"),
    ("Holmes Gin", "Tchula", "MS"),
    ("Linwood Gin", "Vaughan", "MS"),
    ("Mattson Gin", "Clarksdale", "MS"),
    ("Mid-Delta Cotton Processors", "Belzoni", "MS"),
    ("Mill Creek Gin", "Coahoma", "MS"),
    ("North Delta Gin Company", "Marks", "MS"),
    ("Norfolk Corporation Gin", "Cormorant", "MS"),
    ("Quito Gin", "Itta Bena", "MS"),
    ("Scruggs Farm Gin", "Tupelo", "MS"),
    ("Silver Creek Gin", "Holly Bluff", "MS"),
    ("Tri County Gin", "Batesville", "MS"),
    ("Tunica Gin", "Tunica", "MS"),
    ("Yalobusha Gin", "Coffeeville", "MS"),
    ("Yazoo Planters Gin", "Yazoo City", "MS"),
    # Missouri - 18 gins
    ("4-Way Gin Co", "Senath", "MO"),
    ("A C Riley Cotton Co", "New Madrid", "MO"),
    ("Bernie Farmers Gin", "Malden", "MO"),
    ("Bootheel Cotton Co", "Matthews", "MO"),
    ("Cardwell Cooperative, Inc", "Cardwell", "MO"),
    ("Caruthersville Gin Inc.", "Caruthersville", "MO"),
    ("Cooter Cotton Gin Inc.", "Holland", "MO"),
    ("Crowder Cotton Gin", "Sikeston", "MO"),
    ("Dalton Cotton Co", "Senath", "MO"),
    ("Farmers Union Gin", "Senath", "MO"),
    ("J P Ross Cotton Co", "Essex", "MO"),
    ("Mahan Gin", "Parma", "MO"),
    ("McCord Gin", "Gideon", "MO"),
    ("Portageville Farmers Gin, Inc", "Portageville", "MO"),
    ("Richardson Gin", "Marston", "MO"),
    ("Sandy Ridge Cotton Co", "Malden", "MO"),
    ("Stoddard County Cotton Co", "Bernie", "MO"),
    ("Stokes Mayberry Gin", "Malden", "MO"),
    ("Vanduser Gin Co", "Vanduser", "MO"),
    ("White Oak Gin", "White Oak", "MO"),
    # New Mexico - 4 gins
    ("Artesia Alfalfa Growers Association", "Artesia", "NM"),
    ("Farmers CO-OP Assn. GIN #1", "Hagerman", "NM"),
    ("Loving GIN", "Loving", "NM"),
    ("Mesa Farmers Co-op", "Vado", "NM"),
    ("Mesa Farmers CO-OP", "Mesquite", "NM"),
    # North Carolina - 22 gins
    ("Clarkton Cotton Co", "Clarkton", "NC"),
    ("Coastal Carolina Gin", "Pantego", "NC"),
    ("Corner Cotton Gin", "Dunn", "NC"),
    ("Davis Cotton Gin", "Hobgood", "NC"),
    ("Edgecombe Cotton Growers", "Tarboro", "NC"),
    ("Edwards Cotton Co", "Scotland Neck", "NC"),
    ("Enfield Cotton Ginnery", "Enfield", "NC"),
    ("Farmers Gin Co", "Jackson", "NC"),
    ("Gaston Co-op", "Garysburg", "NC"),
    ("Gates Cotton Gin Inc", "Gates", "NC"),
    ("Greene Gin & Cotton Co", "Snow Hill", "NC"),
    ("Growers Ginning Co", "Ayden", "NC"),
    ("Harvey's Gin & Cotton", "La Grange", "NC"),
    ("Hoke Robeson Gin", "Red Springs", "NC"),
    ("Jones County Cotton Gin", "Trenton", "NC"),
    ("Midway Gin Co", "Maxton", "NC"),
    ("Piedmont Cotton Inc", "Polkton", "NC"),
    ("Pitt County Gin", "Bethel", "NC"),
    ("Producer's Gin & Warehouse", "Murfreesboro", "NC"),
    ("Quality Gin Co", "Dunn", "NC"),
    ("Roanoke Cotton Co", "Halifax", "NC"),
    ("Roanoke Tar Cotton Inc", "Everetts", "NC"),
    ("Rolling Hills Gin", "New London", "NC"),
    ("Sampson Gin Co", "Newton Grove", "NC"),
    ("Tarheel Cotton Co", "Merry Hill", "NC"),
    ("Ward & Nixon Cotton Gin", "Winfall", "NC"),
    ("Woodville Gin", "Lewiston-Woodville", "NC"),
    # Kansas - 3 gins
    ("Next GINeration Cotton Gin", "Pratt", "KS"),
    ("Northwest Cotton Growers Co-op", "Moscow", "KS"),
    ("Southern Kansas Cotton Growers", "Anthony", "KS"),
    # Oklahoma - 8 gins
    ("Cotton Growers Co-Op", "Altus", "OK"),
    ("Farmers Co-Op Association", "Eldorado", "OK"),
    ("Farmers Co-op Gin", "Grandfield", "OK"),
    ("Great Plains Cotton Gin", "Minco", "OK"),
    ("Humphreys Co-op", "Altus", "OK"),
    ("Motley Gin Inc.", "Hollis", "OK"),
    ("Tri County Gin", "Chattanooga", "OK"),
    ("Western Planters", "Hobart", "OK"),
    # South Carolina - 11 gins
    ("Cameron Cotton & Seed Co", "Cameron", "SC"),
    ("Coker Gin", "Hartsville", "SC"),
    ("Culler Holstein Gin", "Swansea", "SC"),
    ("Elloree Gin Co", "Elloree", "SC"),
    ("Mayesville Gin Co", "Mayesville", "SC"),
    ("McColl Gin Co", "Bennettsville", "SC"),
    ("MEGCO Services", "Estill", "SC"),
    ("Middling Cotton Co", "St. Matthews", "SC"),
    ("Salters Gin", "Salters", "SC"),
    ("St. Charles Gin Co", "Mayesville", "SC"),
    ("Valentine Cotton Co", "Cope", "SC"),
    # Tennessee - 18 gins
    ("Bemis Gin & Warehouse", "Jackson", "TN"),
    ("Burlison Gin Co", "Covington", "TN"),
    ("Cairo Farmers Gin", "Alamo", "TN"),
    ("Crockett Gin Culverts & Pipe", "Maury City", "TN"),
    ("Crockett Mills Gin", "Friendship", "TN"),
    ("Elora Gin Co", "Elora", "TN"),
    ("Espey Gin Co", "McLemoresville", "TN"),
    ("Farmers Gin Of Humboldt", "Humboldt", "TN"),
    ("Halls Gin Co", "Halls", "TN"),
    ("Hickory Valley Gin Co", "Hickory Valley", "TN"),
    ("Longtown Gin & Warehouse", "Mason", "TN"),
    ("Nutbush Gin Co", "Brownsville", "TN"),
    ("Oak Grove Gin", "Somerville", "TN"),
    ("Tibbs Gin", "Brownsville", "TN"),
    ("Two Way Gin Co", "Brownsville", "TN"),
    ("Union Gin Co", "Brownsville", "TN"),
    ("Yorkville Gin Co", "Dyer", "TN"),
    # Texas - 100+ gins (cottongins.org)
    ("Adobe Walls Gin", "Spearman", "TX"),
    ("Alamo-Kerley Gin", "Saragosa", "TX"),
    ("Associated Cotton Growers", "Saragosa", "TX"),
    ("Barta Gin", "Damon", "TX"),
    ("Barwise Gin", "Floydada", "TX"),
    ("B F & M Co-op", "Rosebud", "TX"),
    ("Birome Gin Co", "Birome", "TX"),
    ("Caprock Gin Co", "Ralls", "TX"),
    ("Carson County Gin", "White Deer", "TX"),
    ("Citizens-Shallowater Co-op Gin", "Shallowater", "TX"),
    ("City Gin", "Abernathy", "TX"),
    ("Coastal Plains Gin", "Mathis", "TX"),
    ("Cotton Center Co-op Gin", "Hale Center", "TX"),
    ("Darty Gin", "Dougherty", "TX"),
    ("D & J Gin", "Lockney", "TX"),
    ("Fairchild Farmers Gin Co-op", "Richmond", "TX"),
    ("Farmers Co-op Gin - East Bernard", "East Bernard", "TX"),
    ("Farmers Gin & Grain Co", "Abbott", "TX"),
    ("Five Points Gin", "Seagraves", "TX"),
    ("Flower Grove Co-op Gin", "Ackerly", "TX"),
    ("Floydada Co-op Gin", "Floydada", "TX"),
    ("Friona Farmers Co-Op Gin", "Friona", "TX"),
    ("Garlyn Co-op Gin", "Post", "TX"),
    ("Hargill Growers Gin", "Monte Alto", "TX"),
    ("Harlingen Gin Co", "Harlingen", "TX"),
    ("Harmony Cotton Growers", "Meadow", "TX"),
    ("Hereford Farmers Gin", "Hereford", "TX"),
    ("Idalou Co-op Gin", "Idalou", "TX"),
    ("Lubbock Cotton Growers", "Lubbock", "TX"),
    ("Maple Co-op Gin", "Maple", "TX"),
    ("Meadow Farmers Co-Op Gin", "Meadow", "TX"),
    ("Midkiff Farmers Co-op Gin", "Midkiff", "TX"),
    ("New Home Co-op", "Meadow", "TX"),
    ("Owens Co-op Gin", "Ralls", "TX"),
    ("Parmer County Cotton Growers", "Farwell", "TX"),
    ("Petersburg Co-op Gin", "Petersburg", "TX"),
    ("Quarterway Cotton Growers", "Plainview", "TX"),
    ("Ropes Farmers Co-op Gin", "Ropesville", "TX"),
    ("Southwest Cotton Growers", "Wellman", "TX"),
    ("Spade Co-Op Gin", "Littlefield", "TX"),
    ("Springlake-Earth Cotton Growers", "Springlake", "TX"),
    ("Tarzan Co-op Gin", "Plains", "TX"),
    ("Texas Producers Co-op", "Sudan", "TX"),
    ("Texas Star Co-op", "Slaton", "TX"),
    ("TriCounty Producers Co-Op", "Loop", "TX"),
    ("True Co-op Gin Co", "Bishop", "TX"),
    ("TXCOT Co-op Gin", "Lorenzo", "TX"),
    ("United Cotton Growers Co-Op", "Levelland", "TX"),
    ("United Ag Co-op", "El Campo", "TX"),
    ("Valley Gin Co", "Tornillo", "TX"),
    ("Vanderbilt Farmers Co-op", "Edna", "TX"),
    ("WesTex Co-op Gin", "Slaton", "TX"),
    ("Wells Farmers Co-op", "O'Donnell", "TX"),
    ("Winter Garden Co-op", "Batesville", "TX"),
    # Virginia
    ("Commonwealth Gin", "Windsor", "VA"),
    ("Commonwealth South Hampton Gin", "Windsor", "VA"),
    ("Hawkins Gin, Inc", "Emporia", "VA"),
    ("Mid-Atlantic Gin", "Emporia", "VA"),
    ("Suffolk Cotton Gin, Inc", "Suffolk", "VA"),
    # Virginia
    ("Commonwealth Gin", "Windsor", "VA"),
    ("Commonwealth South Hampton Gin", "Windsor", "VA"),
    ("Hawkins Gin, Inc", "Emporia", "VA"),
    ("Mid-Atlantic Gin", "Emporia", "VA"),
    ("Suffolk Cotton Gin, Inc", "Suffolk", "VA"),
]


class GinnersSource:
    """Master Cotton Ginners List - cotton gins and grower cooperatives."""

    def get_info(self) -> dict:
        """Return metadata about the ginners list."""
        return {
            "url": MASTER_GINNERS_URL,
            "format": "PDF",
            "description": "List of cotton gins and grower cooperatives",
            "use": "Contact these to reach cotton growers; co-ops are grower-owned",
            "source": "FSA Master Cotton Ginners List + cottongins.org",
        }

    def fetch_ginners(self) -> Iterator[dict]:
        """
        Yield cotton gins and cooperatives (organizations that serve growers).

        Note: These are gins/co-ops, not individual grower names. No public
        complete list of individual cotton growers exists. Contact these
        organizations to reach growers in each region.
        """
        seen = set()
        for name, city, state in COTTON_GINS_AND_COOPS:
            key = (name, city, state)
            if key in seen:
                continue
            seen.add(key)
            yield {
                "name": name,
                "city": city,
                "state": state,
                "type": "cooperative" if "co-op" in name.lower() or "coop" in name.lower() or "growers" in name.lower() else "gin",
                "email": "",
                "phone": "",
                "website": "",
                "buy_link": "",
                "prices": "Contact for quote",
                "source": "FSA Master Cotton Ginners List / cottongins.org",
            }
