"""
USA veal industry sources - farms, processors, and sellers.

Pasture-raised, grass-fed, rose veal, milk-fed, and conventional veal
producers and retailers located in the USA. Includes veal bones, cuts,
and whole/half animals.
"""

import re
from pathlib import Path
from typing import Iterator

CONTACT_FIELDS = ("email", "phone", "website", "buy_link", "prices", "products", "production")

_NOTES_VEAL_TERMS = (
    "pasture raised", "grass fed", "grass finished", "rose veal", "milk fed",
    "free range", "humanely raised", "no antibiotics", "no hormones",
    "organic", "veal chops", "osso buco", "veal bones", "marrow bones",
    "ground veal", "veal cutlet", "veal brisket", "veal shank",
    "veal tenderloin", "veal rack", "veal stew", "veal sausage",
    "whole veal", "half veal", "veal stock", "demi-glace",
    "kosher", "halal", "heritage breed",
)

TYPE_PRODUCTS = {
    "veal_farm": "Veal; pasture-raised; farm direct",
    "veal_processor": "Veal processing; wholesale; food service",
    "veal_retailer": "Veal cuts; bones; online retail",
    "veal_wholesale": "Wholesale veal; food service; bulk",
    "association": "Industry directory; standards; advocacy",
}


def _products_from_notes(notes: str) -> str:
    if not notes:
        return ""
    notes_lower = notes.lower()
    found = []
    for term in _NOTES_VEAL_TERMS:
        if term in notes_lower and term not in found:
            found.append(term.title())
    if found:
        return "; ".join(found[:12])
    return ""


def _production_from_notes(notes: str) -> str:
    if not notes:
        return ""
    m = re.search(r"([\d,\.]+)\+?\s*(?:head|calves?|animals?)\s*(?:/|per)\s*(?:yr|year)", notes, re.I)
    if m:
        return m.group(0).strip()[:50]
    m = re.search(r"([\d,\.]+)\+?\s*(?:employees?|growers?|farms?)", notes, re.I)
    if m:
        return m.group(0).strip()[:50]
    m = re.search(r"(?:since|est\.?|founded)\s+(\d{4})", notes, re.I)
    if m:
        return "Est. " + m.group(1)
    return ""


def _enrich_record(r: dict, default_prices: str = "Contact for pricing") -> dict:
    out = dict(r)
    out.setdefault("email", "")
    out.setdefault("phone", "")
    out.setdefault("website", r.get("url", ""))
    out.setdefault("buy_link", r.get("buy_link", r.get("url", "")))
    out.setdefault("prices", default_prices)
    if not out.get("production"):
        out["production"] = r.get("production") or _production_from_notes(r.get("notes", ""))
    if not out.get("products"):
        out["products"] = (
            r.get("products")
            or _products_from_notes(r.get("notes", ""))
            or TYPE_PRODUCTS.get(out.get("type", ""), "")
        )
    return out


# ---------------------------------------------------------------------------
# Pasture-raised / grass-fed veal farms (direct-to-consumer)
# ---------------------------------------------------------------------------
VEAL_PASTURE_FARMS = [
    {
        "name": "Buffalo Valley Pastures",
        "city": "Quarryville", "state": "PA",
        "url": "https://bvpmarket.com/",
        "website": "https://bvpmarket.com/",
        "buy_link": "https://bvpmarket.com/store/grass-fed-humane-veal",
        "phone": "215-804-6551",
        "email": "milk@bvpmarket.com",
        "type": "veal_farm",
        "notes": "100% grass-fed & finished veal; pasture-raised, never confined; no antibiotics, vaccines, hormones, GMOs; chops, cutlets, ground, cubes, liver, heart, loin; farm pickup + delivery PA/NJ/MD/VA/DC",
        "production": "Family farm; PA",
        "prices": "See website (login required); chops, ground, cutlets, bones",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://bvpmarket.com/",
    },
    {
        "name": "Rossotti Ranch",
        "city": "Petaluma", "state": "CA",
        "url": "https://rossottiranch.com/",
        "website": "https://rossottiranch.com/",
        "buy_link": "https://rossottiranch.com/",
        "phone": "415-717-4033",
        "email": "julie@rossottiranch.com",
        "type": "veal_farm",
        "notes": "CHEAP VEAL BONES $3/lb: 9th-generation family ranch; west Marin + Sonoma Counties; pasture-raised veal; veal bones 20lb $60 ($3/lb, reg $80/$4/lb); bone broth box also avail; calves on mother's milk + native grasses; 6-8 months; ships frozen Tuesdays; 800 Carmody Rd Petaluma CA; Marin farmers market Sun; wholesale avail",
        "production": "9th generation; Marin/Sonoma CA",
        "prices": "VEAL BONES 20lb $60 ($3/lb sale); brisket $100; ground $140; feast $220",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://rossottiranch.com/",
    },
    {
        "name": "Beam Family Farms",
        "city": "Delight", "state": "NC",
        "url": "https://www.beamfamilyfarms.com/",
        "website": "https://www.beamfamilyfarms.com/",
        "buy_link": "https://www.beamfamilyfarms.com/veal",
        "phone": "704-538-1419",
        "email": "luke@bffbeef.com",
        "type": "veal_farm",
        "notes": "Free-range veal; unlimited access to mother's milk + pasture; no antibiotics or hormones; grain-free; conceived, calved, raised on-farm; brisket, ribs, chops, ground, sausage, whole/half veal; online via Barn2Door",
        "production": "Multi-generational family farm",
        "prices": "Chops, ground, ribs, sausage, whole/half veal",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://www.beamfamilyfarms.com/",
    },
    {
        "name": "Possum Tail Farm",
        "city": "Terra Alta", "state": "WV",
        "url": "https://www.possumtailfarm.com/",
        "website": "https://www.possumtailfarm.com/",
        "buy_link": "https://www.possumtailfarm.com/what-we-sell/organic-veal/",
        "phone": "304-789-5556",
        "email": "possumtailfarm@gmail.com",
        "type": "veal_farm",
        "notes": "Rose veal calves raised humanely on grass alongside cattle herd; organic since 2012; 4th generation 148-acre farm; 100% grass-fed; on-farm sales by appointment; delivery to Morgantown WV + Oakland MD",
        "production": "4th generation; 148 acres; organic since 2012",
        "prices": "On-farm by appointment; delivery WV/MD",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://www.possumtailfarm.com/",
    },
    {
        "name": "The Old Road Farm",
        "city": "Washington", "state": "PA",
        "url": "https://theoldroadfarm.com/",
        "website": "https://theoldroadfarm.com/",
        "buy_link": "https://theoldroadfarm.com/store/roseveal",
        "phone": "724-250-8750",
        "email": "farmer@theoldroadfarm.com",
        "type": "veal_farm",
        "notes": "Rose veal; pasture-raised, organic-fed; regenerative farming; online store; weekly Saturday pickup 11am + by appointment; multiple pickup locations + home delivery",
        "production": "Regenerative family farm; PA",
        "prices": "Rose veal cuts; see online store",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://theoldroadfarm.com/",
    },
    {
        "name": "Our Home Place Meat",
        "city": "New Castle", "state": "KY",
        "url": "https://ourhomeplacemeat.com/",
        "website": "https://ourhomeplacemeat.com/",
        "buy_link": "https://ourhomeplacemeat.com/our-beef/",
        "type": "veal_farm",
        "notes": "Rose veal from 100% pasture-raised yearling cattle; Henry County KY family farms; no antibiotics, steroids, hormones; no feedlots; ribeye, NY strip, ground, tenderloin, brisket, osso buco, liver; ships nationwide; 10% off sitewide",
        "production": "KY family farm network",
        "prices": "Ground $45-$90; ribeye $60-$120; sampler $172-$195; free ship $250+",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://ourhomeplacemeat.com/",
    },
    {
        "name": "Springdale Farm and Creamery",
        "city": "Waldo", "state": "ME",
        "url": "https://springdale-farm-store.com/",
        "website": "https://springdale-farm-store.com/",
        "buy_link": "https://farmdrop.us/farm/springdale-farm-and-creamery/",
        "phone": "207-272-5492",
        "type": "veal_farm",
        "notes": "4th generation family farm; Jersey + Guernsey cattle; rose veal raised 5-7 months to 350-400 lbs; cutlets, loin chops, osso buco, bones, ground, sausage; micro-creamery; also on FarmDrop marketplace",
        "production": "4th generation; Waldo ME",
        "prices": "Ground rose veal ~$12/lb; osso buco, chops, bones available",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://farmdrop.us/farm/springdale-farm-and-creamery/",
    },
    {
        "name": "Crosswinds Farm & Creamery",
        "city": "Rock Stream", "state": "NY",
        "url": "https://crosswindsfarmcreamery.com/",
        "website": "https://crosswindsfarmcreamery.com/",
        "buy_link": "https://crosswindsfarmcreamery.com/store/product/veal-marrow-bone",
        "phone": "607-327-0363",
        "email": "crosswindsfarmcreamery@gmail.com",
        "type": "veal_farm",
        "notes": "100% grassfed veal marrow bones; calves raised alongside mothers, weaned 6-8 months; regenerative agriculture; whole bones with knuckle, vacuum-sealed frozen; farm store + scoop shop M-F 7-5, Sa-Su 9-5; online ordering; pickup + delivery NY/PA",
        "production": "Regenerative family farm; Finger Lakes NY",
        "prices": "Veal marrow bones (login for pricing); grassfed dairy + meat",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://crosswindsfarmcreamery.com/",
    },
    {
        "name": "Plumb Rocky Farm",
        "city": "", "state": "NY",
        "url": "https://plumbrockyfarm.com/",
        "website": "https://plumbrockyfarm.com/",
        "buy_link": "https://plumbrockyfarm.com/store/",
        "type": "veal_farm",
        "notes": "Rose veal from Jersey cows; heritage breed; grass-fed, organic feed; calves raised on pasture with mothers; regenerative practices; short ribs, bones, ground, chops",
        "production": "Small heritage farm; NY",
        "prices": "Rose veal cuts; see online store",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://plumbrockyfarm.com/",
    },
    {
        "name": "Misty Brook Farm",
        "city": "Albion", "state": "ME",
        "url": "https://mistybrook.com/",
        "website": "https://mistybrook.com/",
        "buy_link": "https://mistybrook.com/products/the-cows/",
        "phone": "207-437-4719",
        "email": "mistybrookorganic@gmail.com",
        "type": "veal_farm",
        "notes": "Certified organic; 100% grass-fed rose veal; calves raised on mothers/nurse moms; rotationally grazed with sunshine access; self-service farm store open daily dawn-dusk; wholesale + distribution available; inquire about bones + fat",
        "production": "Certified organic family farm; Albion ME",
        "prices": "Contact for organic rose veal + bones pricing",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://mistybrook.com/",
    },
    {
        "name": "Slate Creek Farm",
        "city": "Remsen", "state": "NY",
        "url": "https://slatecreekfarmny.com/",
        "website": "https://slatecreekfarmny.com/",
        "buy_link": "https://slatecreekfarmny.com/product/rose-veal",
        "type": "veal_farm",
        "notes": "Rose veal; ribeye chops $26.50/lb, cutlets $22/lb, loin chops $26/lb, ground $12.50/lb, osso buco $14/lb, bones $4/lb, leg roast $14.95/lb, stew $12.95/lb; farm pickup M/W/F 3-6pm; Oneida County market delivery; home delivery Utica/Rome area; shipping on request",
        "production": "Small family farm; Remsen NY",
        "prices": "Bones $4/lb; ground $12.50/lb; osso buco $14/lb; chops $26-$26.50/lb",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://slatecreekfarmny.com/",
    },
    {
        "name": "B2 Ranch",
        "city": "Buffalo", "state": "TX",
        "url": "https://www.b2ranch.com/",
        "website": "https://www.b2ranch.com/",
        "buy_link": "https://www.b2ranch.com/shop",
        "email": "joebeall.fbg@gmail.com",
        "type": "veal_farm",
        "notes": "Post Oak Savannah region TX; pasture-raised veal; calves raised by mothers on grass; no confinement, antibiotics, or hormones; pink, tender, delicate flavor; chops, cutlets, ground veal; online ordering",
        "production": "Family ranch; Buffalo TX",
        "prices": "Grassfed veal cuts; email for pricing",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://www.b2ranch.com/",
    },
    {
        "name": "Sweet & Salty Farm",
        "city": "Little Compton", "state": "RI",
        "url": "https://sweetandsaltyfarm.com/",
        "website": "https://sweetandsaltyfarm.com/",
        "buy_link": "https://sweetandsaltyfarm.com/grass-fed-veal/",
        "email": "sweetandsaltyfarm@gmail.com",
        "type": "veal_farm",
        "notes": "Small family dairy; Jersey bull calves raised on mothers ~4 months then grazed on fresh daily-rotated pasture; rose veal; also cheese + yogurt creamery; pickup Little Compton Fri-Sun 10-2 + Providence farmers market Sat; no shipping; seasonal availability",
        "production": "Small dairy farm; Little Compton RI",
        "prices": "Seasonal rose veal; check online store",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://sweetandsaltyfarm.com/",
    },
    {
        "name": "Painted Hand Farm",
        "city": "Newburg", "state": "PA",
        "url": "https://paintedhandfarm.com/",
        "website": "https://paintedhandfarm.com/",
        "buy_link": "https://paintedhandfarm.com/",
        "phone": "717-423-5663",
        "type": "veal_farm",
        "notes": "20-acre Civil War-era farm; 30+ years regenerative ag; veal, goat, turkey; rotational grazing, multi-species; no chemicals/mutilation; pasture diversified with grasses, forbs, legumes, native plants; organic vegetables",
        "production": "30+ years regenerative; 20 acres; Newburg PA",
        "prices": "Contact farm for current veal pricing",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://paintedhandfarm.com/",
    },
]

# ---------------------------------------------------------------------------
# Major conventional / milk-fed veal processors (wholesale & foodservice)
# ---------------------------------------------------------------------------
VEAL_PROCESSORS = [
    {
        "name": "Strauss Brands (Strauss Veal)",
        "city": "Franklin", "state": "WI",
        "url": "https://straussbrands.com/",
        "website": "https://straussbrands.com/",
        "buy_link": "https://straussbrands.com/",
        "phone": "800-562-7775",
        "email": "info@straussveal.com",
        "type": "veal_processor",
        "notes": "Founded 1937; family-owned (Randy + Tim Strauss); Free Raised Veal program: calves stay with mother 18-22 wks, 400-500 lbs, Limousin-influenced; all-natural, no antibiotics/hormones; also conventional milk-fed; largest US veal processor",
        "production": "Est. 1937; largest US veal processor",
        "prices": "Wholesale/foodservice; Free Raised + conventional programs",
        "raising": "both",
        "source": "web", "source_url": "https://straussbrands.com/",
    },
    {
        "name": "Marcho Farms",
        "city": "Souderton", "state": "PA",
        "url": "https://marchofarms.com/",
        "website": "https://marchofarms.com/",
        "buy_link": "https://marchofarms.grazecart.com/",
        "phone": "800-313-7131",
        "email": "ltufft@marchofarms.com",
        "type": "veal_processor",
        "notes": "Major US veal producer; USDA-certified Marcho Farms Premium Veal program; Souderton PA; wholesale + direct sales via GrazeCart; Dr. Linda Tufft quality assurance; milk-fed + grain-fed programs",
        "production": "Major US processor; Souderton PA",
        "prices": "Wholesale + retail via GrazeCart",
        "raising": "conventional",
        "source": "web", "source_url": "https://marchofarms.com/",
    },
    {
        "name": "Catelli Brothers",
        "city": "Pennsauken", "state": "NJ",
        "url": "https://catellibrothers.com/",
        "website": "https://catellibrothers.com/",
        "buy_link": "https://catellibrothers.com/veal",
        "phone": "856-910-1016",
        "type": "veal_processor",
        "notes": "75+ years; veal + lamb; NJ + MA processing facilities; group-housed, untethered calves; specialty steaks, grinds, marinated proteins; foodservice + retail; value-added product line",
        "production": "Est. ~1950; 75+ years; NJ + MA facilities",
        "prices": "Wholesale/foodservice; value-added cuts",
        "raising": "conventional",
        "source": "web", "source_url": "https://catellibrothers.com/",
    },
    {
        "name": "Atlantic Veal & Lamb (Plume De Veau)",
        "city": "Brooklyn", "state": "NY",
        "url": "https://atlanticvealandlamb.com/",
        "website": "https://atlanticvealandlamb.com/",
        "buy_link": "https://atlanticvealandlamb.com/plumebrands/",
        "phone": "718-599-6400",
        "type": "veal_processor",
        "notes": "Founded 1956; 3 generations; Plume De Veau brand; fully integrated: feed plants, calf barns, butcheries; 50+ independent growers across 4 states; 100% tether-free group housing; USDA facilities in NE Ohio + Brooklyn NY; Ohio State University welfare certification; M-F 6am-4:30pm",
        "production": "Est. 1956; 50+ growers; 4 states; 2 USDA plants",
        "prices": "Wholesale/foodservice; Plume De Veau + Epicurean + Farm Fed brands",
        "raising": "conventional",
        "source": "web", "source_url": "https://atlanticvealandlamb.com/",
    },
    {
        "name": "Midwest Veal",
        "city": "North Manchester", "state": "IN",
        "url": "",
        "type": "veal_processor",
        "notes": "Country's top veal producer; North Manchester IN; president Steve Anderson; sprawling production facilities; converted to modern group housing over 7 yrs starting 2005; sister company Strauss Feeds (Watertown WI); Indiana is #1 veal-producing state",
        "production": "#1 US veal producer; North Manchester IN",
        "prices": "Wholesale/foodservice",
        "raising": "conventional",
        "source": "web", "source_url": "https://www.americanveal.com/",
    },
]

# ---------------------------------------------------------------------------
# Online retailers / butchers selling veal (bones, cuts, etc.)
# ---------------------------------------------------------------------------
VEAL_RETAILERS = [
    {
        "name": "Victorian Farmstead Meat Company",
        "city": "Sebastopol", "state": "CA",
        "url": "https://new.vicfarmmeats.com/",
        "website": "https://new.vicfarmmeats.com/",
        "buy_link": "https://new.vicfarmmeats.com/product-category/pasture-raised-beef-veal/veal/",
        "phone": "707-332-4605",
        "email": "adam@vicfarmmeats.com",
        "type": "veal_retailer",
        "notes": "Butcher in Community Market Sebastopol; sources from Rossotti Ranch; pasture-raised veal; rib chops $42/lb, osso buco $5, cutlet $10, tenderloin $15, porterhouse $12, top sirloin $12, ground $13, stew $14.50, bones $5/lb; local delivery $15 + nationwide shipping",
        "production": "Sebastopol CA butcher",
        "prices": "Bones $5/lb; ground $13; chops $42/lb; osso buco $5; tenderloin $15",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://new.vicfarmmeats.com/",
    },
    {
        "name": "Grow & Behold (Kosher Pastured Meats)",
        "city": "Brooklyn", "state": "NY",
        "url": "https://www.growandbehold.com/",
        "website": "https://www.growandbehold.com/",
        "buy_link": "https://www.growandbehold.com/rose-veal/",
        "phone": "888-790-5781",
        "email": "info@growandbehold.com",
        "type": "veal_retailer",
        "notes": "Kosher pastured rose veal; pasture-fed, never penned; no hormones/antibiotics; veal bones $12.99/lb, marrow bones $18.49/lb; rib chops, ground, scaloppini, stew, osso buco, short ribs; multiple kosher certifications (Star-K, OU, Beit Yosef); ships nationwide frozen; NY/NJ local delivery",
        "production": "US family farms; Brooklyn NY HQ",
        "prices": "Bones $12.99/lb; marrow $18.49/lb; chops, ground, osso buco",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://www.growandbehold.com/",
    },
    {
        "name": "DeBragga",
        "city": "New York", "state": "NY",
        "url": "https://www.debragga.com/",
        "website": "https://www.debragga.com/",
        "buy_link": "https://www.debragga.com/veal.html",
        "phone": "646-873-6555",
        "type": "veal_retailer",
        "notes": "New York's Butcher; milk-fed veal from 120 farms in OH + PA; Holstein calves; no hormones, no sub-therapeutic antibiotics; osso buco 6-pack $226, frenched rack chops 4-pack $170; glace de veau $27; fresh overnight delivery; serves legendary chefs",
        "production": "120 farms; OH + PA sourced",
        "prices": "Osso buco 6pk $226; rack chops 4pk $170; glace de veau $27",
        "raising": "conventional",
        "source": "web", "source_url": "https://www.debragga.com/",
    },
    {
        "name": "D'Artagnan",
        "city": "Union", "state": "NJ",
        "url": "https://www.dartagnan.com/",
        "website": "https://www.dartagnan.com/",
        "buy_link": "https://www.dartagnan.com/buy/veal/",
        "phone": "800-327-8246",
        "type": "veal_retailer",
        "notes": "Gourmet meat purveyor; milk-fed veal (French Charolais/Limousin imported + domestic); humanely raised, no antibiotics/hormones; Milanese chops $46-$47; striploin, racks, shanks; 12 veal products; $15 flat shipping; 15% off $199+",
        "production": "Major gourmet retailer",
        "prices": "Milanese chops $46-$47; rack, shanks, striploin; $15 flat ship",
        "raising": "conventional",
        "source": "web", "source_url": "https://www.dartagnan.com/",
    },
    {
        "name": "Exceptional Foods",
        "city": "Pennsauken", "state": "NJ",
        "url": "https://www.exfoods.com/",
        "website": "https://www.exfoods.com/",
        "buy_link": "https://www.exfoods.com/products/veal/",
        "phone": "215-739-8450",
        "email": "orders@exfoods.com",
        "type": "veal_wholesale",
        "notes": "Wholesale meat distributor NJ/PA/DE; sources Plume De Veau milk-fed veal; tether-free, Ohio State certified; top round, medallions, shank, osso buco, bones, demi-glace, chops, cheeks, sweetbreads, breast; new accounts call sales team",
        "production": "Wholesale distributor; NJ/PA/DE territory",
        "prices": "Wholesale; call 215-739-8450 for pricing",
        "raising": "conventional",
        "source": "web", "source_url": "https://www.exfoods.com/",
    },
    {
        "name": "Provimi Foods",
        "city": "", "state": "",
        "url": "https://provimifoods.com/",
        "website": "https://provimifoods.com/",
        "buy_link": "https://provimifoods.com/our-products/",
        "phone": "800-833-8325",
        "type": "veal_wholesale",
        "notes": "Veal demi-glace specialist; Traditional (#97877 16lb case), Supreme (#97077 20lb case), Halal (#97477 20lb case); roasted veal bones, ready-to-use sauces; gluten-free, starch-free; foodservice wholesale",
        "production": "Major demi-glace producer",
        "prices": "Traditional 16lb case; Supreme 20lb case; Halal 20lb case; wholesale",
        "raising": "conventional",
        "source": "web", "source_url": "https://provimifoods.com/",
    },
    {
        "name": "Chicago Wholesale Meats (Northwest Meat Co)",
        "city": "Chicago", "state": "IL",
        "url": "https://www.chicagowholesalemeats.com/",
        "website": "https://www.chicagowholesalemeats.com/",
        "buy_link": "https://www.chicagowholesalemeats.com/product/wholesale-veal/",
        "type": "veal_wholesale",
        "notes": "Chicago wholesale meat distributor; veal osso buco, shanks, chops, ground, various wholesale cuts; foodservice + restaurant supply",
        "production": "Wholesale distributor; Chicago IL",
        "prices": "Wholesale; veal osso buco 14oz, chops, shanks",
        "raising": "conventional",
        "source": "web", "source_url": "https://www.chicagowholesalemeats.com/",
    },
    {
        "name": "Fischer Bros & Leslie",
        "city": "New York", "state": "NY",
        "url": "https://www.fischerbros.com/",
        "website": "https://www.fischerbros.com/",
        "buy_link": "https://www.fischerbros.com/products/597",
        "type": "veal_retailer",
        "notes": "Kosher butcher/retailer; veal shank osso buco $29.98/lb; premium veal cuts; New York City",
        "production": "NYC kosher butcher",
        "prices": "Osso buco $29.98/lb; premium veal cuts",
        "raising": "conventional",
        "source": "web", "source_url": "https://www.fischerbros.com/",
    },
    {
        "name": "Halperns' Steak & Seafood",
        "city": "Atlanta", "state": "GA",
        "url": "https://halperns.com/",
        "website": "https://halperns.com/",
        "buy_link": "https://halperns.com/our-products/veal/",
        "phone": "866-659-6090",
        "type": "veal_wholesale",
        "notes": "Gourmet wholesale; milk-fed + range-fed veal; custom cutting; 7 locations: Atlanta GA, Ft Lauderdale/Naples/Orlando FL, Baltimore MD, Arlington TX, Walton KY, Kalamazoo MI; osso buco, racks, chops, custom cuts; part of GFS family",
        "production": "7 US locations; national wholesale",
        "prices": "Wholesale; milk-fed + range-fed veal; custom cut",
        "raising": "both",
        "source": "web", "source_url": "https://halperns.com/",
    },
    {
        "name": "Pritzlaff Wholesale Meats",
        "city": "New Berlin", "state": "WI",
        "url": "https://pritzlaffmeats.com/",
        "website": "https://pritzlaffmeats.com/",
        "buy_link": "http://www.pritzlaffmeats.com/OUR-PRODUCTS/VEAL",
        "phone": "866-290-0507",
        "type": "veal_wholesale",
        "notes": "Wisconsin wholesale meats; Dutch veal: racks, chops, ribeye, breast, osso buco, short ribs, tenderloin, cutlets; all-natural; M-F 8am-4:30pm CST; fax orders 24/7; restaurant + foodservice",
        "production": "Wholesale distributor; New Berlin WI",
        "prices": "Wholesale; Dutch veal cuts; call for pricing",
        "raising": "conventional",
        "source": "web", "source_url": "https://pritzlaffmeats.com/",
    },
    {
        "name": "Weiss Meats",
        "city": "Pittsburgh", "state": "PA",
        "url": "https://www.weissmeats.com/",
        "website": "https://www.weissmeats.com/",
        "buy_link": "https://www.weissmeats.com/store/wholesale",
        "phone": "800-870-0545",
        "email": "orders@weissmeats.com",
        "type": "veal_wholesale",
        "notes": "Since 1948; Pittsburgh wholesale; serves PA/WV/OH; grocers, restaurants, caterers; veal + custom cuts; 5-6 day delivery; M-Sa 8am-6pm",
        "production": "Est. 1948; PA/WV/OH territory",
        "prices": "Wholesale; custom-cut + portioning; special orders",
        "raising": "conventional",
        "source": "web", "source_url": "https://www.weissmeats.com/",
    },
    {
        "name": "Alony Glatt (Kosher Grass Fed)",
        "city": "Davie", "state": "FL",
        "url": "https://alonyglatt.com/",
        "website": "https://alonyglatt.com/",
        "buy_link": "https://alonyglatt.com/collections/veal",
        "phone": "954-483-9909",
        "email": "AlonyGlatt@gmail.com",
        "type": "veal_retailer",
        "notes": "Kosher (glatt) grass-fed veal; osso buco $15.99/lb; veal chop $32.99/lb; half veal ~$13.99/lb; 100% USA born/raised/processed; Sun-Thu 9am-8pm, Fri 9am-2pm; nationwide delivery",
        "production": "Online kosher retailer; Davie FL",
        "prices": "Osso buco $15.99/lb; chop $32.99/lb; half veal $13.99/lb",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://alonyglatt.com/",
    },
    {
        "name": "KOSH",
        "city": "", "state": "NY",
        "url": "https://www.kosh.com/",
        "website": "https://www.kosh.com/",
        "buy_link": "https://www.kosh.com/kosher-veal.html",
        "phone": "845-295-5152",
        "type": "veal_retailer",
        "notes": "Premium kosher veal; PA milk-fed; Marble & Grain brand; 2-bone rib chops $54.99/lb; hand-cut, vacuum-sealed, frozen; Star-K Glatt certified; free ground shipping $350+; ships M-Thu",
        "production": "PA milk-fed veal; online kosher retail",
        "prices": "Rib chops $54.99/lb; case of 10 ~$336; free ship $350+",
        "raising": "conventional",
        "source": "web", "source_url": "https://www.kosh.com/",
    },
    {
        "name": "Lobel's of New York",
        "city": "New York", "state": "NY",
        "url": "https://www.lobels.com/",
        "website": "https://www.lobels.com/",
        "buy_link": "https://www.lobels.com/all-natural-veal-25",
        "phone": "877-783-4512",
        "type": "veal_retailer",
        "notes": "Premier NYC butcher since 1840; all-natural milk-fed veal from upper Midwest; hormone + antibiotic-free; chops, roasts, cutlets, ground, osso buco, stew, CulinArte Glace de Veau; ships nationwide; legendary quality",
        "production": "Est. 1840; upper Midwest sourced",
        "prices": "Strip steak $30-$33; chops, roasts, cutlets, glace de veau",
        "raising": "conventional",
        "source": "web", "source_url": "https://www.lobels.com/",
    },
    {
        "name": "Prairie Street (Kosher)",
        "city": "", "state": "",
        "url": "https://prairiestreet.co/",
        "website": "https://prairiestreet.co/",
        "buy_link": "https://prairiestreet.co/collections/veal",
        "email": "info@prairiestreet.co",
        "type": "veal_retailer",
        "notes": "Star-K kosher veal; pasture-fed, humanely raised on US family farms; rib chops $52; paillard, cutlets, ground, osso buco; free 3-day shipping US $100+; 10% subscription discount; WhatsApp ordering",
        "production": "US family farm sourced",
        "prices": "Rib chops $52; free 3-day ship $100+; 10% sub discount",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://prairiestreet.co/",
    },
    {
        "name": "Fossil Farms",
        "city": "Boonton", "state": "NJ",
        "url": "https://www.fossilfarms.com/",
        "website": "https://www.fossilfarms.com/",
        "buy_link": "https://www.fossilfarms.com/",
        "phone": "973-917-3155",
        "type": "veal_retailer",
        "notes": "Specialty + game meat retailer; retail store + online; 81 Fulton St Boonton NJ; free shipping $199+; store pickup available 24hr notice; M-F 9-5; veal, game meats, exotic proteins",
        "production": "Specialty retailer; Boonton NJ",
        "prices": "Free shipping $199+; specialty cuts; call for veal availability",
        "raising": "conventional",
        "source": "web", "source_url": "https://www.fossilfarms.com/",
    },
    {
        "name": "Pat LaFrieda Meat Purveyors",
        "city": "North Bergen", "state": "NJ",
        "url": "https://www.lafrieda.com/",
        "website": "https://www.lafrieda.com/",
        "buy_link": "https://shop.lafrieda.com/collections/veal",
        "type": "veal_retailer",
        "notes": "Largest veal distributor in New York; milk-fed veal from Mennonite + Amish family farms; humanely raised in group housing; Temple Grandin-designed facilities; rib chops 12oz + 16oz, porterhouse chops 14oz; online + wholesale via chefandrestaurantsupply.com",
        "production": "Largest NYC veal distributor",
        "prices": "Rib chops, porterhouse; wholesale + online retail",
        "raising": "conventional",
        "source": "web", "source_url": "https://shop.lafrieda.com/",
    },
    {
        "name": "S. Ottomanelli & Sons",
        "city": "Queens", "state": "NY",
        "url": "https://ottomanelli.com/",
        "website": "https://ottomanelli.com/",
        "buy_link": "https://ottomanelli.com/product-category/veal/",
        "phone": "718-651-5544",
        "type": "veal_retailer",
        "notes": "NYC butcher; natural milk-fed veal; loin chops $15-$45, rib chops $15-$45, cutlets $23, osso buco $65; antibiotic-free, hormone-free, vegetarian-fed; ships nationwide; 60-15 Woodside Ave Queens NY",
        "production": "NYC butcher; Queens + Greenwich Village",
        "prices": "Chops $15-$45; cutlets $23; osso buco $65",
        "raising": "conventional",
        "source": "web", "source_url": "https://ottomanelli.com/",
    },
    {
        "name": "Vincent's Meat Market",
        "city": "Bronx", "state": "NY",
        "url": "https://vincentsmeatmarket.com/",
        "website": "https://vincentsmeatmarket.com/",
        "buy_link": "https://vincentsmeatmarket.com/product-category/veal/",
        "phone": "718-295-9048",
        "email": "theservice@vincentsmeatmarket.com",
        "type": "veal_retailer",
        "notes": "Since 1954; Arthur Ave Bronx; family-owned; hand-cut never-frozen; cutlets $34, rib chops $41-$60, osso buco $45-$180, stew $22; ships nationwide + NYC local delivery; M-Sa 9-5; text 929-736-2110",
        "production": "Est. 1954; Arthur Ave Bronx",
        "prices": "Cutlets $34; chops $41-$60; osso buco $45-$180; stew $22",
        "raising": "conventional",
        "source": "web", "source_url": "https://vincentsmeatmarket.com/",
    },
    {
        "name": "Citarella",
        "city": "New York", "state": "NY",
        "url": "https://www.citarella.com/",
        "website": "https://www.citarella.com/",
        "buy_link": "https://www.citarella.com/shop",
        "phone": "212-874-0383",
        "type": "veal_retailer",
        "notes": "Premium NYC grocer; ground veal $17.49/lb; veal chops, cutlets; same-day delivery or pickup; nationwide overnight shipping $35-$70; min $75 order; M-Sa 9-7, Sun 10-6; multiple NYC locations",
        "production": "Premium retailer; multiple NYC locations",
        "prices": "Ground veal $17.49/lb; overnight ship $35-$70; min $75",
        "raising": "conventional",
        "source": "web", "source_url": "https://www.citarella.com/",
    },
    {
        "name": "Farmingdale Meat Market",
        "city": "Farmingdale", "state": "NY",
        "url": "https://farmingdalemeatmarket.com/",
        "website": "https://farmingdalemeatmarket.com/",
        "buy_link": "https://farmingdalemeatmarket.com/collections/veal",
        "phone": "516-249-8200",
        "email": "info@mainstreetmeats.com",
        "type": "veal_retailer",
        "notes": "Since 1946; family-owned Long Island butcher; bones $4.13/lb, ground 2lb $16.54, rib chops $27.16, porterhouse $16.20, osso buco $20.81/14oz; also Main Street Wholesale for restaurants; free local delivery $200+; nationwide 3-4 day ship; M-Sa 9-6, Sun 9-3",
        "production": "Est. 1946; Long Island NY",
        "prices": "Bones $4.13/lb; ground $8.27/lb; chops $27; osso buco $21",
        "raising": "conventional",
        "source": "web", "source_url": "https://farmingdalemeatmarket.com/",
    },
    {
        "name": "Cappuccio's Meats",
        "city": "Philadelphia", "state": "PA",
        "url": "https://shop.cappuccios.com/",
        "website": "https://shop.cappuccios.com/",
        "buy_link": "https://shop.cappuccios.com/products/631760724a98d1002f02054f/fresh-veal-stock-bones",
        "phone": "215-922-5792",
        "email": "cappucciosmeats@comcast.net",
        "type": "veal_retailer",
        "notes": "Italian Market Philadelphia; fresh veal stock bones $5.99/lb; online shop + in-store; 1019 S 9th St Philadelphia PA",
        "production": "Italian Market butcher; Philadelphia PA",
        "prices": "Veal stock bones $5.99/lb; fresh cuts",
        "raising": "conventional",
        "source": "web", "source_url": "https://shop.cappuccios.com/",
    },
    {
        "name": "Paulina Market",
        "city": "Chicago", "state": "IL",
        "url": "https://www.paulinamarket.com/",
        "website": "https://www.paulinamarket.com/",
        "buy_link": "https://www.paulinamarket.com/products/veal-bones",
        "phone": "773-248-6272",
        "type": "veal_retailer",
        "notes": "Classic Chicago butcher; Wisconsin veal; bones $10.95/~1.5lb; full veal selection; M-F 9-6, Sa 9-5; 3501 N Lincoln Ave Chicago IL; Ask the Butcher feature",
        "production": "Chicago butcher; Wisconsin veal sourced",
        "prices": "Bones $10.95/1.5lb; full veal counter",
        "raising": "conventional",
        "source": "web", "source_url": "https://www.paulinamarket.com/",
    },
    {
        "name": "Springfield Butcher",
        "city": "Springfield", "state": "VA",
        "url": "https://www.springfieldbutcher.com/",
        "website": "https://www.springfieldbutcher.com/",
        "buy_link": "https://www.springfieldbutcher.com/product/Veal-Bones",
        "phone": "703-245-0111",
        "email": "info@springfieldbutcher.com",
        "type": "veal_retailer",
        "notes": "Since 1977; veal bones $5.99/1.5lb avg; online ordering with in-store pickup; serves DC/MD/VA area; Tu-Sa 10-6, Sun 10-3; 6310B Springfield Plaza Springfield VA",
        "production": "Est. 1977; Springfield VA",
        "prices": "Veal bones $5.99/1.5lb; full butcher counter",
        "raising": "conventional",
        "source": "web", "source_url": "https://www.springfieldbutcher.com/",
    },
    {
        "name": "Amos Miller Organic Farm",
        "city": "Bird-in-Hand", "state": "PA",
        "url": "https://amosmillerorganicfarm.com/",
        "website": "https://amosmillerorganicfarm.com/",
        "buy_link": "https://amosmillerorganicfarm.com/product-category/meats-only/milk-fed-and-grass-finished-veal/",
        "phone": "717-556-0672",
        "type": "veal_farm",
        "notes": "Organic Amish farm; milk-fed + grass-finished veal; no hormones, antibiotics, GMO, drugs, or vaccines; ground veal $11.50/lb, marrow bones $17.50/lb, veal broth $8.50/pint; also beef tallow $6.50-$11/pint-qt; Private Member Association; ships M-Thu; min $50 order",
        "production": "Organic Amish farm; Bird-in-Hand PA",
        "prices": "Marrow bones $17.50/lb; ground $11.50/lb; broth $8.50/pt; beef tallow $6.50-$11",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://amosmillerorganicfarm.com/",
    },
    {
        "name": "Harmony Acres",
        "city": "", "state": "",
        "url": "https://harmonyacres.com/",
        "website": "https://harmonyacres.com/",
        "buy_link": "https://harmonyacres.com/store/beef/veal",
        "phone": "888-711-8777",
        "type": "veal_farm",
        "notes": "100% grass-fed veal; food ministry model (membership donations); rotationally grazed year-round; no pesticides or chemicals; multiple pickup locations across USA + home delivery; raw dairy, pastured eggs, pork, chicken also available",
        "production": "Multi-state pickup network",
        "prices": "Membership/donation model; 100% grass-fed veal",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://harmonyacres.com/",
    },
    {
        "name": "Star Dairy (Rose Veal)",
        "city": "", "state": "",
        "url": "https://stardairy.weebly.com/",
        "website": "https://stardairy.weebly.com/",
        "buy_link": "https://stardairy.weebly.com/rose-veal.html",
        "email": "staressence@gmail.com",
        "type": "veal_farm",
        "notes": "Rose veal from dairy bull calves; raised on mother's milk + fresh grass spring/summer; butchered in fall; whole animal $6/lb hanging weight + butchering; half $6.50/lb; seasonal availability",
        "production": "Small family dairy; seasonal fall harvest",
        "prices": "Whole $6/lb hanging wt; half $6.50/lb + butchering",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://stardairy.weebly.com/",
    },
    {
        "name": "Porter and York",
        "city": "", "state": "",
        "url": "https://porterandyork.com/",
        "website": "https://porterandyork.com/",
        "buy_link": "https://porterandyork.com/product/buy-veal-osso-bucco-online/",
        "email": "hey@porterandyork.com",
        "type": "veal_retailer",
        "notes": "Pasture-raised veal osso buco 2-pack $54; natural Angus, harvested 18-20 wks (400-500 lbs); Midwest family farms; grass-fed grain-finished; creamy pink color, velvety texture; ships frozen nationwide",
        "production": "Midwest family farm sourced",
        "prices": "Osso buco 2-pack $54; pasture-raised",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://porterandyork.com/",
    },
    {
        "name": "Kansas City Steaks",
        "city": "Kansas City", "state": "MO",
        "url": "https://www.kansascitysteaks.com/",
        "website": "https://www.kansascitysteaks.com/",
        "buy_link": "https://www.kansascitysteaks.com/beef/veal",
        "phone": "877-377-8325",
        "type": "veal_retailer",
        "notes": "Premium veal online; osso buco $215-$365 (hind shank 1lb each, wet-aged); rib chops bone-in wet-aged; ships nationwide (except CA/MA due to legislation); 10% off $100+ site-wide; includes cooking guide",
        "production": "Major online meat retailer",
        "prices": "Osso buco $215-$365; rib chops; 10% off $100+",
        "raising": "conventional",
        "source": "web", "source_url": "https://www.kansascitysteaks.com/",
    },
    {
        "name": "Grand Western Steaks",
        "city": "", "state": "",
        "url": "https://grandwesternsteaks.com/",
        "website": "https://grandwesternsteaks.com/",
        "buy_link": "https://grandwesternsteaks.com/veal-osso-bucco-domestic.html",
        "phone": "877-624-6898",
        "type": "veal_retailer",
        "notes": "American veal osso bucco + frenched veal chops; ships nationwide; M-F 8-5; loyalty rewards program; Give $20 Get $20 promo",
        "production": "Online meat retailer",
        "prices": "Osso bucco; frenched chops; call for pricing",
        "raising": "conventional",
        "source": "web", "source_url": "https://grandwesternsteaks.com/",
    },
    {
        "name": "Savenor's Market",
        "city": "Boston", "state": "MA",
        "url": "https://savenorsbutchery.com/",
        "website": "https://savenorsbutchery.com/",
        "buy_link": "https://savenorsbutchery.com/collections/veal",
        "phone": "617-723-6328",
        "type": "veal_retailer",
        "notes": "Premium Boston butcher; veal rib chops, loin chops, shank osso bucco, sweetbreads; ships nationwide online; 2 locations: 160 Charles St Boston + 92 Kirkland St Cambridge; same-day Cambridge delivery before 11am",
        "production": "Premium butcher; Boston + Cambridge",
        "prices": "Premium veal cuts; rib chops, osso buco, sweetbreads",
        "raising": "conventional",
        "source": "web", "source_url": "https://savenorsbutchery.com/",
    },
    {
        "name": "Baldor Specialty Foods",
        "city": "Bronx", "state": "NY",
        "url": "https://www.baldorfood.com/",
        "website": "https://www.baldorfood.com/",
        "buy_link": "https://www.baldorfood.com/farms/atlantic-veal-and-lamb",
        "phone": "718-860-9100",
        "type": "veal_wholesale",
        "notes": "Premier NYC wholesale food distributor; carries Plume De Veau (Atlantic Veal & Lamb); serves restaurants, hotels, food markets; Northeast coverage; M-F 9-5",
        "production": "Major NYC wholesale distributor",
        "prices": "Wholesale; Plume De Veau + specialty meats",
        "raising": "conventional",
        "source": "web", "source_url": "https://www.baldorfood.com/",
    },
]

# ---------------------------------------------------------------------------
# Pasture-raised / grass-fed suet & tallow sellers (bones + fat)
# ---------------------------------------------------------------------------
SUET_TALLOW = [
    {
        "name": "White Oak Pastures",
        "city": "Bluffton", "state": "GA",
        "url": "https://whiteoakpastures.com/",
        "website": "https://whiteoakpastures.com/",
        "buy_link": "https://whiteoakpastures.com/products/grassfed-beef-suet",
        "type": "veal_retailer",
        "notes": "Since 1866; regenerative farm; grassfed beef suet + raw fat; also bones, organs; free ship $249+; $15 perishable ship $149+; Bluffton GA; one of largest pasture-raised operations in US",
        "production": "Est. 1866; major regenerative farm; Bluffton GA",
        "prices": "Grassfed suet; free ship $249+; $15 ship $149+",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://whiteoakpastures.com/",
    },
    {
        "name": "Bastrop Cattle Company",
        "city": "Bastrop", "state": "TX",
        "url": "https://www.bastropcattlecompany.com/",
        "website": "https://www.bastropcattlecompany.com/",
        "buy_link": "https://www.bastropcattlecompany.com/shop/p/suet",
        "phone": "512-537-6893",
        "email": "sales@BastropCattleCompany.com",
        "type": "veal_retailer",
        "notes": "Woman-owned; 100% grass-fed grass-finished beef suet; vacuum-sealed 2-3lb packs; 10lb $7.50/lb, 20lb $7.25/lb, 40lb $7/lb; no antibiotics/hormones; no retail store, online + email only; ranch pickup by appt",
        "production": "Small ranch; Bastrop TX",
        "prices": "Suet 10lb $7.50/lb; 20lb $7.25/lb; 40lb $7/lb; +$20 TX ship",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://www.bastropcattlecompany.com/",
    },
    {
        "name": "Beaver Brook Ranch",
        "city": "Hope", "state": "NJ",
        "url": "https://beaverbrookranch.com/",
        "website": "https://beaverbrookranch.com/",
        "buy_link": "https://beaverbrookranch.com/product/grass-fed-bulk-tallow-rendered-suet/",
        "phone": "908-509-7102",
        "type": "veal_retailer",
        "notes": "Grass-fed rendered tallow from 100% suet; dry-rendered triple-filtered; gallon (7lb) $18/lb ($126); 42+lb $15.30/lb; tallow balm $15-$77; farm store Sa 9-12, Fr 9-3; free ship $250+ eastern US; cGMP audited",
        "production": "Family farm; Hope NJ",
        "prices": "Bulk tallow 7lb $126 ($18/lb); 42lb+ $15.30/lb; balm $15-$77",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://beaverbrookranch.com/",
    },
    {
        "name": "REP Provisions",
        "city": "Bixby", "state": "OK",
        "url": "https://repprovisions.com/",
        "website": "https://repprovisions.com/",
        "buy_link": "https://repprovisions.com/products/rep-regenerative-beef-suet",
        "email": "Kim@repprovisions.com",
        "type": "veal_retailer",
        "notes": "Regenerative grass-fed beef suet (kidney fat); 2lb $22.95 ($20.66 subscribe); free ship $175+ meat orders; 2-3 day UPS/FedEx; ships M-W; safe arrival guarantee; 48 continental US states",
        "production": "Regenerative sourced; Bixby OK",
        "prices": "Suet 2lb $22.95; subscribe 10% off; free ship $175+",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://repprovisions.com/",
    },
    {
        "name": "Tyner Pond Farm",
        "city": "Greenfield", "state": "IN",
        "url": "https://tynerpondfarm.com/",
        "website": "https://tynerpondfarm.com/",
        "buy_link": "https://tynerpondfarm.com/products/beef-suet",
        "phone": "317-477-7940",
        "email": "amber@farmersmarket.com",
        "type": "veal_retailer",
        "notes": "100% grass-fed pasture-raised beef suet; ~2lb $30; cattle rotated daily on pasture; never grain-fed; no antibiotics/hormones; free local delivery $63+ Indianapolis area; Greenfield IN",
        "production": "Family farm; Greenfield IN",
        "prices": "Suet ~2lb $30; free local delivery $63+",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://tynerpondfarm.com/",
    },
    {
        "name": "1915 Farm",
        "city": "Meyersville", "state": "TX",
        "url": "https://1915farm.com/",
        "website": "https://1915farm.com/",
        "buy_link": "https://1915farm.com/products/grassfed-beef-cooking-tallow",
        "phone": "361-333-5295",
        "email": "1915farm@1915farm.com",
        "type": "veal_retailer",
        "notes": "Grass-fed cooking tallow rendered from suet; 10oz glass jar $9.99; also raw suet ~1.5lb $9.99; hand-rendered small batch; ships nationwide UPS M-Tu on dry ice; ship from $29.99 TX; no hormones/antibiotics",
        "production": "Family farm; Meyersville TX",
        "prices": "Tallow 10oz $9.99; raw suet 1.5lb $9.99; ship from $29.99",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://1915farm.com/",
    },
    {
        "name": "Svec Farm",
        "city": "Estelline", "state": "SD",
        "url": "https://www.svecfarm.com/",
        "website": "https://www.svecfarm.com/",
        "buy_link": "https://www.svecfarm.com/product/beef-suet/",
        "phone": "605-873-4770",
        "email": "info@svecfarm.com",
        "type": "veal_retailer",
        "notes": "CHEAPEST BONES: 5th generation farm; heritage Belted Galloway cattle; grass-finished; bulk bones 33lb box $33 (~$1/lb!!!); suet ~3.5lb $19.60 (reg $28); no corn/soy/grain/antibiotics/GMO/hormones; pickup only: on-farm Estelline, Brookings, Sioux Falls SD; does not ship",
        "production": "5th generation; Estelline SD",
        "prices": "BONES 33lb $33 (~$1/lb); Suet 3.5lb $19.60 (sale); pickup only SD",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://www.svecfarm.com/",
    },
    {
        "name": "Apsey Farms",
        "city": "", "state": "MI",
        "url": "https://apseyfarms.com/",
        "website": "https://apseyfarms.com/",
        "buy_link": "https://apseyfarms.com/products/beef-suet",
        "type": "veal_retailer",
        "notes": "100% grass-fed beef suet; regeneratively raised; ships continental US $99 min order; local delivery Grand Rapids MI area; also beef, pork, chicken, eggs",
        "production": "Regenerative farm; Grand Rapids MI area",
        "prices": "Grass-fed suet; $99 min order; ships continental US",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://apseyfarms.com/",
    },
    {
        "name": "Rowe Family Farms",
        "city": "Cleveland", "state": "TN",
        "url": "https://rowefarmstn.com/",
        "website": "https://rowefarmstn.com/",
        "buy_link": "https://rowefarmstn.com/products/grass-fed-beef-fat",
        "phone": "423-650-2891",
        "email": "rowefarmstn@gmail.com",
        "type": "veal_retailer",
        "notes": "Grass-fed beef kidney fat (suet); 1-1.5lb $7.50, 1.5-2lb $10, 2.1-2.5lb $12.50, 2.5-3lb $15; free local delivery $45+; nationwide shipping; also half/whole beef; Cleveland TN",
        "production": "Family farm; Cleveland TN",
        "prices": "Suet 1-1.5lb $7.50; 2.5-3lb $15; free local $45+",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://rowefarmstn.com/",
    },
    {
        "name": "Tussock Sedge Farm",
        "city": "Perkasie", "state": "PA",
        "url": "https://tussocksedgefarm.com/",
        "website": "https://tussocksedgefarm.com/",
        "buy_link": "https://tussocksedgefarm.com/store/product/beef-fat-suet",
        "phone": "267-450-4024",
        "email": "info@tussocksedgefarm.com",
        "type": "veal_retailer",
        "notes": "100% grass-fed Red Angus; beef suet $6.99/lb (~5lb avg); raised nearly 3 years on pasture; no grain/chemicals/hormones/vaccines/antibiotics; dry-aged; on-farm pickup only M-Sa 8-6; Perkasie PA",
        "production": "Family farm; Perkasie PA",
        "prices": "Suet $6.99/lb (~5lb avg); on-farm pickup only",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://tussocksedgefarm.com/",
    },
    {
        "name": "Primal Pastures",
        "city": "Murrieta", "state": "CA",
        "url": "https://primalpastures.com/",
        "website": "https://primalpastures.com/",
        "buy_link": "https://primalpastures.com/products/beef-suet",
        "email": "info@primalpastures.com",
        "type": "veal_retailer",
        "notes": "Grass-fed grass-finished beef suet 2lb $16; Northern CA + AZ ranches; no antibiotics/hormones; ships nationwide M-W (M-Thu western states); 25391 Washington Ave Murrieta CA; W/F 9-3, Sa 9-12",
        "production": "Multi-ranch sourced; Murrieta CA",
        "prices": "Suet 2lb $16; ships nationwide",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://primalpastures.com/",
    },
    {
        "name": "US Wellness Meats",
        "city": "Canton", "state": "MO",
        "url": "https://grasslandbeef.com/",
        "website": "https://grasslandbeef.com/",
        "buy_link": "https://grasslandbeef.com/collections/tallow-marrow-broth",
        "phone": "877-383-0051",
        "email": "eathealthy@grasslandbeef.com",
        "type": "veal_retailer",
        "notes": "Major grass-fed online retailer; tallow 1.7lb $17.46, 1gal $101, 5gal $202; suet 5lb $38.52; marrow bones 1lb $11.28, 1.75lb $19.29, canoe-cut 5lb $79.95; knuckle bones 8oz $10.66; free ship 15lb+; M-F 8:30-4:30 CST",
        "production": "Major online retailer; Canton MO",
        "prices": "Suet 5lb $38.52; tallow 1.7lb $17.46; marrow 1lb $11.28; free ship 15lb+",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://grasslandbeef.com/",
    },
    {
        "name": "Porter Road",
        "city": "Nashville", "state": "TN",
        "url": "https://porterroad.com/",
        "website": "https://porterroad.com/",
        "buy_link": "https://porterroad.com/products/beef-bones",
        "phone": "855-877-8202",
        "type": "veal_retailer",
        "notes": "Nashville butcher + online; pasture-raised beef bones ~$6/lb, marrow bones $15/lb, beef tallow 32oz; renders tallow in-house; no antibiotics/hormones; butcher shop Tu-Sa 11-6; 501 Gallatin Ave Nashville; flat-rate ship $125+",
        "production": "Nashville butcher shop + online",
        "prices": "Bones ~$6/lb; marrow $15/lb; tallow 32oz; flat ship $125+",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://porterroad.com/",
    },
    {
        "name": "Homeplace Pastures",
        "city": "Como", "state": "MS",
        "url": "https://homeplacepastures.com/",
        "website": "https://homeplacepastures.com/",
        "buy_link": "https://homeplacepastures.com/products/grass-fed-beef-marrow-bones-new",
        "phone": "662-426-6191",
        "email": "info@homeplacepastures.com",
        "type": "veal_retailer",
        "notes": "Grass-fed marrow bones 3lb $14 (~$4.67/lb); center-cut with exposed marrow; free ship $250+ UPS Ground; $15 flat $150+; on-farm pickup available; 1630 Home Place Rd Como MS",
        "production": "Family farm; Como MS",
        "prices": "Marrow bones 3lb $14 ($4.67/lb); free ship $250+",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://homeplacepastures.com/",
    },
    {
        "name": "Sweet Mercy Farms",
        "city": "Albuquerque", "state": "NM",
        "url": "https://www.sweetmercyfarms.com/",
        "website": "https://www.sweetmercyfarms.com/",
        "buy_link": "https://www.sweetmercyfarms.com/grassfed-beef-cuts/beef-marrow-bones",
        "type": "veal_retailer",
        "notes": "Grass-fed marrow bones $9/lb; marrow-only (roasting) or marrow+knuckle (broth); 1-4.5lb packs; farm pickup M-F 8-5; local Albuquerque $5 delivery; metro $10; ground ship select SW states; 6991 Jensen Dr SW Albuquerque",
        "production": "Family farm; Albuquerque NM",
        "prices": "Marrow bones $9/lb; local delivery $5-$10",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://www.sweetmercyfarms.com/",
    },
    {
        "name": "Silo Springs Ranch",
        "city": "Culloden", "state": "GA",
        "url": "https://www.silospringsranch.com/",
        "website": "https://www.silospringsranch.com/",
        "buy_link": "https://www.silospringsranch.com/store/p/beef-marrow-bones",
        "phone": "678-852-9880",
        "type": "veal_retailer",
        "notes": "Grass-fed grass-finished marrow bones ~1.5lb $10 ($6.67/lb); USDA certified; air-aged 14 days; processed 15 mi from ranch; general store + farmers markets; on Hwy 341 Culloden GA",
        "production": "Family ranch; Culloden GA",
        "prices": "Marrow bones ~1.5lb $10 ($6.67/lb)",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://www.silospringsranch.com/",
    },
    {
        "name": "The Family Bee's-ness",
        "city": "Franklinton", "state": "NC",
        "url": "https://www.thefamilybeesness.com/",
        "website": "https://www.thefamilybeesness.com/",
        "buy_link": "https://www.thefamilybeesness.com/store/p/beef-stew-meat-kktjk-nklzl",
        "phone": "919-986-2592",
        "type": "veal_retailer",
        "notes": "Pasture-raised Black Angus; marrow bones 1.85lb $7 ($9/lb); regenerative ag, organic hay; weekday pickup 9-5 by appt, Sa 9-12 open farm; 354 Garner Rd Franklinton NC",
        "production": "Regenerative farm; Franklinton NC",
        "prices": "Marrow bones 1.85lb $7 ($9/lb)",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://www.thefamilybeesness.com/",
    },
    {
        "name": "Oregon Valley Farm",
        "city": "Jefferson", "state": "OR",
        "url": "https://oregonvalleyfarm.com/",
        "website": "https://oregonvalleyfarm.com/",
        "buy_link": "https://store.oregonvalleyfarm.com/product/beef-marrow-bones-portioned/",
        "phone": "888-822-3848",
        "type": "veal_retailer",
        "notes": "Grass-fed grass-finished marrow bones 24oz $19.99 ($13.32/lb); 2 bones/pack; also grain-finished option; Pacific NW farms; pickup Albany OR; $50 off first order $149+ code JOINUS50",
        "production": "PNW farm partners; Jefferson OR",
        "prices": "Marrow bones 24oz $19.99 ($13.32/lb); $50 off first $149+",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://oregonvalleyfarm.com/",
    },
    {
        "name": "Elkins Cattle Co",
        "city": "Lampasas", "state": "TX",
        "url": "https://elkinscattleco.com/",
        "website": "https://elkinscattleco.com/",
        "buy_link": "https://elkinscattleco.com/products/marrow-bones",
        "email": "info@elkinscattleco.com",
        "type": "veal_retailer",
        "notes": "USDA Prime+ grass-fed Angus; marrow bones 4pk canoe-cut $16; dry-aged 15+ days; no hormones/steroids/mRNA; ships Mon 1-2 day UPS; Sunday noon CT cutoff; currently only available in beef boxes; Lampasas TX",
        "production": "Family ranch; Lampasas TX",
        "prices": "Marrow bones 4pk $16 (in beef boxes); dry-aged 15+ days",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://elkinscattleco.com/",
    },
    {
        "name": "Casey Redtail Ranch",
        "city": "King City", "state": "CA",
        "url": "https://caseyredtailranch.com/",
        "website": "https://caseyredtailranch.com/",
        "buy_link": "https://caseyredtailranch.com/products/grassfed-beef-marrow-bones-10-pounds",
        "email": "rich@caseyredtailranch.com",
        "type": "veal_retailer",
        "notes": "Grassfed beef marrow bones 10lb vacuum-packed; 100% pasture-raised; no antibiotics/hormones; free ship CA; nationwide available; local pickup King City CA; processing 1 day-3 months seasonal",
        "production": "Family ranch; King City CA",
        "prices": "Marrow bones 10lb pack; free ship CA; nationwide",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://caseyredtailranch.com/",
    },
    {
        "name": "Eel River Organic Beef",
        "city": "Hydesville", "state": "CA",
        "url": "https://eelriverorganicbeef.com/",
        "website": "https://eelriverorganicbeef.com/",
        "buy_link": "https://eelriverorganicbeef.com/product/organic-grass-fed-beef-mixed-soup-broth-bones/",
        "type": "veal_retailer",
        "notes": "Certified organic grass-fed grass-finished; mixed soup/broth bones $18.99; marrow bones 3lb $15.11; knuckle+marrow mix; ships frozen dry ice nationwide; free ship ground $199+; wholesale via Tony's Fine Foods CA; M-F 9-4",
        "production": "Organic ranch; Humboldt County CA",
        "prices": "Soup bones $18.99; marrow 3lb $15.11; free ship $199+",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://eelriverorganicbeef.com/",
    },
    {
        "name": "The Fat Lady",
        "city": "", "state": "WI",
        "url": "https://thefatladytallow.com/",
        "website": "https://thefatladytallow.com/",
        "buy_link": "https://thefatladytallow.com/products/bulk-size-premium-grass-fed-beef-tallow-fat",
        "type": "veal_retailer",
        "notes": "Premium grass-fed tallow from Wisconsin family farms; artisanal dry-rendered double-filtered; 60oz $59.99, 1gal $106.66; 3.5gal drums available; subscribe 5% off; free US ship $45+; USDA inspected; Etsy 4.9 stars 12.4k sales",
        "production": "WI family farm sourced; artisanal",
        "prices": "Tallow 60oz $59.99; 1gal $106.66; free ship $45+",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://thefatladytallow.com/",
    },
    {
        "name": "EPIC Provisions",
        "city": "Austin", "state": "TX",
        "url": "https://epicprovisions.com/",
        "website": "https://epicprovisions.com/",
        "buy_link": "https://epicprovisions.com/collections/animal-fats",
        "type": "veal_retailer",
        "notes": "100% grass-fed beef tallow 11oz jar $13.89; Keto/Whole30 approved; gluten-free; also at Sprouts ($14.99), Lucky ($17.49), other retail; free ship $50+ direct; 10% subscription discount; major national brand",
        "production": "National brand; Austin TX",
        "prices": "Tallow 11oz $13.89 direct; $14.99-$17.49 retail; free ship $50+",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://epicprovisions.com/",
    },
    {
        "name": "Essential Depot",
        "city": "", "state": "FL",
        "url": "https://www.essentialdepot.com/",
        "website": "https://www.essentialdepot.com/",
        "buy_link": "https://www.essentialdepot.com/product/TALLOW-50LB-BOX.html",
        "phone": "863-224-9555",
        "type": "veal_wholesale",
        "notes": "CHEAP BULK TALLOW: grass-fed beef tallow 50lb $164.74 ($3.29/lb, 50% off); food grade; free US shipping; not hydrogenated; non-GMO, USP compliant; no lactose/gluten/BSE; Greener Life Club additional 20% off; M-F 1-5pm; text Melanie for partner program",
        "production": "Bulk supplier; FL",
        "prices": "Tallow 50lb $164.74 ($3.29/lb); FREE US SHIP; 20% more off w/ club",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://www.essentialdepot.com/",
    },
    {
        "name": "Sulu Organics",
        "city": "", "state": "IL",
        "url": "https://www.suluorganics.com/",
        "website": "https://www.suluorganics.com/",
        "buy_link": "https://www.suluorganics.com/products/wholesale-of-50-lbs-high-non-gmo-beef-tallow-food-grade",
        "phone": "630-855-2190",
        "email": "support@thesulu.com",
        "type": "veal_wholesale",
        "notes": "Grass-fed beef tallow; 4lb $34.99 ($8.75/lb), 7lb avail, 50lb $230 ($4.60/lb); USDA food-grade; pasture-raised US cows; no hormones/vaccines/antibiotics; non-GMO; 9mo shelf; free ship US $35+; 25% off $500+",
        "production": "Bulk supplier; IL",
        "prices": "Tallow 4lb $34.99; 50lb $230 ($4.60/lb); free ship $35+",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://www.suluorganics.com/",
    },
    {
        "name": "Stryker Farm",
        "city": "", "state": "PA",
        "url": "https://www.strykerfarm.com/",
        "website": "https://www.strykerfarm.com/",
        "buy_link": "https://www.strykerfarm.com/store/p106/GrassFedBeefSuet.html",
        "phone": "484-750-4588",
        "email": "info@strykerfarm.com",
        "type": "veal_retailer",
        "notes": "CHEAP SUET: grass-fed beef suet 20lb $84.99 ($4.25/lb), 40lb $119.99 ($3/lb); USDA inspected; free ship Eastern USA; Pocono Mountains PA; currently backordered; also tallow rendering",
        "production": "Family farm; Pocono Mountains PA",
        "prices": "Suet 20lb $84.99 ($4.25/lb); 40lb $119.99 ($3/lb); free ship East",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://www.strykerfarm.com/",
    },
    {
        "name": "Rural Reverie",
        "city": "", "state": "",
        "url": "https://ruralreverie.com/",
        "website": "https://ruralreverie.com/",
        "buy_link": "https://ruralreverie.com/products/beef-bones-2-75-lb",
        "type": "veal_retailer",
        "notes": "CHEAP BONES: grass-fed beef broth bones $3/lb; pasture-raised; no antibiotics/hormones; 5lb packs (often sold out); also whole/half beef orders",
        "production": "Family farm",
        "prices": "Bones $3/lb (5lb packs); whole/half beef avail",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://ruralreverie.com/",
    },
    {
        "name": "JH Grass Fed",
        "city": "", "state": "AZ",
        "url": "https://jhgrassfed.com/",
        "website": "https://jhgrassfed.com/",
        "buy_link": "https://jhgrassfed.com/product/beef-marrow-and-knuckle-bones-grass-fed-grass-finished/",
        "type": "veal_retailer",
        "notes": "Grass-fed grass-finished marrow+knuckle bones $4.50/lb (~5lb avg); soup/neck bones $6.54/lb; locally processed dry-aged; AZ Dept of Ag inspected; 45mi N of Cave Creek AZ; valley pickup or delivery; email for exact weight + pricing",
        "production": "Family ranch; north of Cave Creek AZ",
        "prices": "Marrow bones $4.50/lb; neck bones $6.54/lb",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://jhgrassfed.com/",
    },
    {
        "name": "Pettit Pastures",
        "city": "Milaca", "state": "MN",
        "url": "https://www.pettitpastures.com/",
        "website": "https://www.pettitpastures.com/",
        "buy_link": "https://www.pettitpastures.com/product/grass-fed-marrowbones/",
        "phone": "320-293-3560",
        "email": "pettitpastures@gmail.com",
        "type": "veal_retailer",
        "notes": "Minnesota's finest grass-fed beef; marrow bones + knuckles; 9341 125th Ave Milaca MN; online shop + local; contact for pricing",
        "production": "Family farm; Milaca MN",
        "prices": "Marrow bones; contact for pricing",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://www.pettitpastures.com/",
    },
    {
        "name": "Together Farms",
        "city": "Mondovi", "state": "WI",
        "url": "https://togetherfarms.com/",
        "website": "https://togetherfarms.com/",
        "buy_link": "https://togetherfarms.com/store/grass-fed-beef/bones",
        "phone": "715-210-4740",
        "email": "steph@togetherfarms.com",
        "type": "veal_retailer",
        "notes": "100% grass-fed grass-finished bones; Animal Welfare Approved butcher; organs+bones 10lb bundle $64 (was $100); flat $9 ship or free; farm pickup Mondovi WI; local delivery Buffalo/Chippewa/Eau Claire counties; overnight select states",
        "production": "Family farm; Mondovi WI",
        "prices": "Organs+bones 10lb $64; flat $9 ship; free options",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://togetherfarms.com/",
    },
    {
        "name": "S Ranch Meats",
        "city": "", "state": "",
        "url": "https://sranchmeats.com/",
        "website": "https://sranchmeats.com/",
        "buy_link": "https://sranchmeats.com/products/premium-ranch-raised-beef-suet-un-rendered-tallow-bulk-box",
        "type": "veal_retailer",
        "notes": "Ranch-raised beef suet bulk box; 25x 1lb packs $187.50 ($7.50/lb); ground for easy rendering; yields ~18-22lb tallow; free ship $175+",
        "production": "Ranch direct",
        "prices": "Suet 25lb $187.50 ($7.50/lb); free ship $175+",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://sranchmeats.com/",
    },
    {
        "name": "Bolster Farm",
        "city": "Stratford", "state": "NY",
        "url": "https://bolsterfarm.grazecart.com/",
        "website": "https://bolsterfarm.grazecart.com/",
        "buy_link": "https://bolsterfarm.grazecart.com/store/product/pork-bones",
        "type": "veal_retailer",
        "notes": "ULTRA CHEAP BONES: grass-fed beef bones $1/lb (sale, reg $2-3/lb); ~4lb avg pkg; broth/soup/dog bones; no hormones; Stratford NY; online order via GrazeCart",
        "production": "Family farm; Stratford NY",
        "prices": "Bones $1/lb (sale); reg $2-3/lb; ~4lb pkgs",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://bolsterfarm.grazecart.com/",
    },
    {
        "name": "Shady Grove Ranch",
        "city": "Jefferson", "state": "TX",
        "url": "https://shadygroveranch.grazecart.com/",
        "website": "https://shadygroveranch.net/",
        "buy_link": "https://shadygroveranch.grazecart.com/store/beef/bones-broth",
        "phone": "903-665-7076",
        "type": "veal_retailer",
        "notes": "CHEAP BONES: grass-fed soup bones $3.25/3-5lb pkg; meaty soup bones $6.50/2-3lb; custom harvest bones $1/lb bulk; farm store Th 2-5, Fr 10-3, Sa 10-1; pickup Longview/Marshall/Tyler/Shreveport; 559 Shady Grove Rd Jefferson TX",
        "production": "Family ranch; Jefferson TX",
        "prices": "Soup bones $3.25/pkg; meaty $6.50/pkg; bulk harvest $1/lb",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://shadygroveranch.net/",
    },
    {
        "name": "Grove Ladder Farm",
        "city": "", "state": "FL",
        "url": "https://groveladderfarmllc.grazecart.com/",
        "website": "https://groveladderfarmllc.grazecart.com/",
        "buy_link": "https://groveladderfarmllc.grazecart.com/store/broth-bones/bones",
        "type": "veal_retailer",
        "notes": "100% grass-fed grass-finished Florida Cracker beef; bones single $7/lb, 2-pack $5.50/lb, 3-pack $4/lb; neck bones $7/lb; split marrow $9/lb; ships within FL; local pickup; regenerative",
        "production": "Family farm; FL",
        "prices": "Bones $7/lb single, $5.50 2-pk, $4/lb 3-pk; neck $7; marrow $9",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://groveladderfarmllc.grazecart.com/",
    },
    {
        "name": "Circle J Meat",
        "city": "Houston", "state": "TX",
        "url": "https://circlejmeat.com/",
        "website": "https://circlejmeat.com/",
        "buy_link": "https://circlejmeat.com/products/grass-fed-beef-bones",
        "phone": "979-399-7362",
        "type": "veal_retailer",
        "notes": "CHEAP BONES $3/lb: 100% grass-fed grass-finished beef bones 5lb bag $15 ($3/lb); various lengths; some w/ meat attached; no grain/antibiotics/GMO/hormones; meethouse 1521 Antoine Dr Houston TX; GrazeCart orders; pickup locations in TX",
        "production": "Family farm; Houston TX",
        "prices": "Bones 5lb bag $15 ($3/lb)",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://circlejmeat.com/",
    },
    {
        "name": "Livengood Family Farm",
        "city": "Lancaster", "state": "PA",
        "url": "https://livengoodfamilyfarm.com/",
        "website": "https://livengoodfamilyfarm.com/",
        "buy_link": "https://livengoodfamilyfarm.com/store/product/beef-bag-of-bones",
        "phone": "717-327-6817",
        "type": "veal_retailer",
        "notes": "VERY CHEAP BONES: 100% grass-fed grass-finished; bag of bones 10lb $2.45/lb; marrow bones $6.50/lb; born+raised on farm; 1648 Morningside Dr Lancaster PA 17602; farm pickup + Clark Park Farmers Market",
        "production": "Family farm; Lancaster PA",
        "prices": "Bag of bones 10lb avg $2.45/lb; marrow $6.50/lb",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://livengoodfamilyfarm.com/",
    },
    {
        "name": "Chandler Pond Farm",
        "city": "Wheelock", "state": "VT",
        "url": "https://www.chandlerpondfarm.com/",
        "website": "https://www.chandlerpondfarm.com/",
        "buy_link": "https://www.chandlerpondfarm.com/shop/beef-suet-for-tallow",
        "type": "veal_retailer",
        "notes": "CHEAPEST SUET: grass-fed grain-free suet from $4/pkg (under 1lb up to 4lb sizes); perfect for rendering tallow; USDA inspected; dry-aged 14+ days; 528 Burroughs Rd Wheelock VT 05851; farmstand open daily 8am-8pm; online + pickup",
        "production": "Family farm; Wheelock VT",
        "prices": "Suet from $4/pkg (various sizes); farmstand pickup",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://www.chandlerpondfarm.com/",
    },
    {
        "name": "Rangeland Revival",
        "city": "Wilton", "state": "IA",
        "url": "https://rangelandrevival.com/",
        "website": "https://rangelandrevival.com/",
        "buy_link": "https://rangelandrevival.com/store/beef/bones",
        "phone": "563-299-7934",
        "email": "Jr@rangelandrevival.com",
        "type": "veal_retailer",
        "notes": "100% grass-fed pasture-raised; soup bones $6/lb (sale, reg $8.95/lb); oxtail $9.49/lb; no antibiotics; 1930 Rose Ave Wilton IA 52778; online + delivery + pickup",
        "production": "Family ranch; Wilton IA",
        "prices": "Soup bones $6/lb (sale); oxtail $9.49/lb",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://rangelandrevival.com/",
    },
    {
        "name": "Meat and Cheese Head",
        "city": "", "state": "",
        "url": "https://meatandcheesehead.com/",
        "website": "https://meatandcheesehead.com/",
        "buy_link": "https://meatandcheesehead.com/products/beef-tallow-50-lbs-bulk-food-grade-100-beef-tallow",
        "type": "veal_wholesale",
        "notes": "CHEAPEST TALLOW FOUND: 50lb bulk beef tallow $135 ($2.70/lb!!!); 100% pure; food grade; cooking/baking/skincare; free US shipping",
        "production": "Bulk supplier",
        "prices": "Tallow 50lb $135 ($2.70/lb); FREE US SHIP",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://meatandcheesehead.com/",
    },
    {
        "name": "Thousand Hills Lifetime Grazed",
        "city": "Becker", "state": "MN",
        "url": "https://thousandhillslifetimegrazed.com/",
        "website": "https://thousandhillslifetimegrazed.com/",
        "buy_link": "https://thousandhillslifetimegrazed.com/product/bulk-beef-tallow/",
        "phone": "877-854-8422",
        "email": "info@thousandhillsgrassfed.com",
        "type": "veal_wholesale",
        "notes": "CHEAP TALLOW + SUET: 100% grass-fed AGA certified; bulk tallow case (4x 8lb) from $49.99; suet case (4x 0.75lb) $14.99-$17.49; regenerative; 12925 Prosperity Ave Becker MN; free ship $249+",
        "production": "Major grass-fed brand; Becker MN",
        "prices": "Tallow case 32lb from $49.99 (~$1.56/lb); suet case $14.99; free ship $249+",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://thousandhillslifetimegrazed.com/",
    },
    {
        "name": "Graze Cattle Company",
        "city": "Eaton", "state": "CO",
        "url": "https://grazecattlecompany.com/",
        "website": "https://grazecattlecompany.com/",
        "buy_link": "https://grazecattlecompany.com/products/beef-soup-bones-1lb",
        "type": "veal_retailer",
        "notes": "CHEAP BONES: grass-fed grass-finished Black Angus soup bones $2.99/lb (sale from $3.99); 2 bones/pkg w/ marrow+collagen; no hormones/antibiotics; free local delivery 25mi on $100+; Eaton CO; often sold out",
        "production": "Family ranch; Eaton CO",
        "prices": "Soup bones $2.99/lb (sale); free local $100+",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://grazecattlecompany.com/",
    },
    {
        "name": "Grassway Organics",
        "city": "East Troy", "state": "WI",
        "url": "https://grasswayorganics.grazecart.com/",
        "website": "https://www.grasswayorganics.com/",
        "buy_link": "https://grasswayorganics.next.grazecart.com/store/product/beef-soup-bones",
        "phone": "920-894-4201",
        "email": "webstore@grasswayorganics.com",
        "type": "veal_retailer",
        "notes": "CHEAP BONES: 100% grass-fed beef stock bones $2.99/lb (sale from $4.19); ~3lb avg; W2716 Friemoth Rd East Troy WI 53120; farm store T-Sa 10-6; online + multiple WI pickup locations + home delivery",
        "production": "Family farm; East Troy WI",
        "prices": "Stock bones $2.99/lb (sale); farm store + delivery",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://www.grasswayorganics.com/",
    },
    {
        "name": "Autumn's Harvest Farm",
        "city": "Romulus", "state": "NY",
        "url": "https://autumnsharvestfarmpasturedmeats.com/",
        "website": "https://autumnsharvestfarmpasturedmeats.com/",
        "buy_link": "https://autumnsharvestfarmpasturedmeats.com/store/grass-fed-beef/bones",
        "phone": "315-400-0802",
        "email": "info@autumnsharvestfarmpasturedmeats.com",
        "type": "veal_retailer",
        "notes": "AWA certified grass-fed; bones+organs; 5170 Kings Corners Rd Romulus NY 14541; free ship $149+; 5% subscribe+save; local delivery free $75+",
        "production": "Family farm; Romulus NY (Finger Lakes)",
        "prices": "Bones avail; free ship $149+; 5% subscribe discount",
        "raising": "pasture_raised",
        "source": "web", "source_url": "https://autumnsharvestfarmpasturedmeats.com/",
    },
]

# ---------------------------------------------------------------------------
# Industry associations
# ---------------------------------------------------------------------------
VEAL_ASSOCIATIONS = [
    {
        "name": "American Veal Association (AVA)",
        "city": "", "state": "",
        "url": "https://www.americanveal.com/",
        "type": "association",
        "notes": "Founded 1984; member-driven; advocates for milk-fed veal quality, innovation, collaboration; Veal Quality Assurance (VQA) program; Five Domains of Animal Welfare standards; group housing, no tethering",
        "source": "web", "source_url": "https://www.americanveal.com/",
    },
]


class VealSource:
    """USA veal industry sources - farms, processors, retailers."""

    def __init__(self):
        pass

    def _yield_enriched(self, items: list, default_prices: str = "Contact for pricing") -> Iterator[dict]:
        for r in items:
            yield _enrich_record(r, default_prices)

    def fetch_all(self) -> Iterator[dict]:
        """Yield all veal sources."""
        for r in self._yield_enriched(VEAL_PASTURE_FARMS):
            yield r
        for r in self._yield_enriched(VEAL_PROCESSORS):
            yield r
        for r in self._yield_enriched(VEAL_RETAILERS):
            yield r
        for r in self._yield_enriched(SUET_TALLOW):
            yield r
        for r in self._yield_enriched(VEAL_ASSOCIATIONS):
            yield r

    def fetch_pasture_raised(self) -> Iterator[dict]:
        """Yield only pasture-raised / grass-fed veal farms."""
        yield from self._yield_enriched(VEAL_PASTURE_FARMS)

    def fetch_processors(self) -> Iterator[dict]:
        yield from self._yield_enriched(VEAL_PROCESSORS)

    def fetch_retailers(self) -> Iterator[dict]:
        yield from self._yield_enriched(VEAL_RETAILERS)

    def fetch_associations(self) -> Iterator[dict]:
        yield from self._yield_enriched(VEAL_ASSOCIATIONS)
